apiVersion: 1

datasources:
  - name: NR5103
    type: influxdb
    url: http://influxdb:8086
    database: nr5103
    user: nr5103
    jsonData:
      httpMethod: POST
    secureJsonData:
      password: nr5103password
    access: proxy
    editable: true
    isDefault: false

  - name: NR5103 Flux
    type: influxdb
    url: http://influxdb:8086
    database: nr5103
    user: nr5103
    jsonData:
      httpMethod: POST
      version: Flux
      organization: nr5103
      defaultBucket: nr5103
    secureJsonData:
      token: nr5103token
    access: proxy
    editable: true
    isDefault: false